version: 2

jobs:
  build-test-8_6_3:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: cabal new-update
      - restore_cache:
          keys:
            - cabal-index-{{ checksum "~/.cabal/packages/hackage.haskell.org/01-index.cache" }}-v1
      - run: make build
      - run: make test
      - save_cache:
          key: cabal-index-{{ checksum "~/.cabal/packages/hackage.haskell.org/01-index.cache" }}-v1
          paths:
            - ~/.cabal
      - persist_to_workspace:
          root: .
          paths:
            - dist-newstyle
  generate:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: cabal new-update
      - restore_cache:
          keys:
            - cabal-index-{{ checksum "~/.cabal/packages/hackage.haskell.org/01-index.cache" }}-v1
      - run: git config --global user.email "ci@example.com"
      - run: git config --global user.name "ci-build"
      - run: git checkout -B docs
      - run: git rebase master
      - attach_workspace:
          at: .
      - run: git clone --depth 1 https://gitlab.haskell.org/ghc/ghc.git output/ghc
      - run: make generate
      - run: git add -f docs/notes/
      - run: git status
      - run: git remote add gh-release "https://${GITHUB_TOKEN}@github.com/myuon/ghc-compiler-notes.git"
      - run: git commit -m 'build' && git push gh-release docs

workflows:
  version: 2

  # When test has passed, tag a release
  build_and_test:
    jobs:
      - build-test-8_6_3:
          filters:
            branches:
              ignore:
                - docs
      - generate:
          requires:
            - build-test-8_6_3
          filters:
            branches:
              only:
                - master
