version: 2.1

orbs:
  haskell: haskell-works/haskell-build@1.6.3

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.6.3
          executor: haskell/ghc-8_6_3
          run-check: false
          after-test:
            - run: cabal new-test --enable-tests -fdev
      - haskell/build:
          requires:
            - haskell/build
          filters:
            branches:
              only: master
          executor: haskell/ghc-8_6_3
          run-tests: false
          run-check: false
          after-test:
            - run: make generate
