version: 2

jobs:
  build-test-8_6_3:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: cabal new-update
      - restore_cache:
          keys:
            - cabal-index-{{ checksum "~/.cabal/packages/hackage.haskell.org/01-index.cache" }}
      - run: make build
      - save_cache:
          key: cabal-index-{{ checksum "~/.cabal/packages/hackage.haskell.org/01-index.cache" }}
          paths:
            - ~/.cabal
      - run: make test
      - persist_to_workspace:
          root: .
          paths:
            - .
  generate:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - attach_workspace:
          at: .
      - run: make generate

workflows:
  version: 2

  # When test has passed, tag a release
  build_and_test:
    jobs:
      - build-test-8_6_3
      - generate:
          requires:
            - build-test-8_6_3
