version: 2

jobs:
  build-test-8_6_3:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: cabal new-update
      - run: make build
      - run: make test
      - persist_to_workspace:
          root: .
          paths:
            - .
  generate:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - attach_workspace:
          at: .
      - run: cabal new-update
      - run: make generate
      - run: git config --global user.email "ci@example.com"
      - run: git config --global user.name "ci-build"
      - run: git add docs/notes/ && git commit -m '[ci] build' && git push -f origin master

workflows:
  version: 2
  build:
    jobs:
      - build-test-8_6_3
      - generate:
          requires:
            - build-test-8_6_3
          filters:
            branches:
              only: master
