version: 2

jobs:
  build-test-8_6_3:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - run: cabal new-update
      - run: make build
      - run: make test
      - persist_to_workspace:
          root: .
          paths:
            - .
  generate:
    working_directory: ~/workspace
    docker:
      - image: haskell:8.6.3
    steps:
      - attach_workspace:
          at: .
      - run: make generate

workflows:
  version: 2
  build:
    jobs:
      - build-test-8_6_3
      - generate:
          requires:
            - build-test-8_6_3
          filters:
            branches:
              only: master
